# [[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  # package = "@netlify/plugin-lighthouse"

# branch = master
[build.environment]
  NODE_VERSION = "19.9.0"
  NPM_VERSION = "9.6.6"

# branch
# [context.staging]
# [context.staging.environment]

# branch = dev
# [context.dev]
# [context.dev.environment]

# [context.deploy-preview]
# [context.deploy-preview.environment]

# [context.branch-deploy]
# [context.branch-deploy.environment]

# [context.staging]
# [context.staging.environment]

# [context.dev]
# [context.dev.environment]
